/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author usuario
 */
public class MenuPrincipal extends javax.swing.JFrame {
    Biblioteca b = new Biblioteca();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarLibro = new javax.swing.JButton();
        btnAgregarUsuario = new javax.swing.JButton();
        btnPrestarLibro = new javax.swing.JButton();
        btnMostrarLibros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnMostrarUsuarios = new javax.swing.JButton();
        btnMostrarPrestamos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregarLibro.setText("Agregar Libro");
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });

        btnAgregarUsuario.setText("Agregar  Usuario ");
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });

        btnPrestarLibro.setText("Prestar Libro");
        btnPrestarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarLibroActionPerformed(evt);
            }
        });

        btnMostrarLibros.setText("Mostrar Libros");
        btnMostrarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarLibrosActionPerformed(evt);
            }
        });

        jLabel1.setText("SISTEMA BIBLIOTECA");

        btnMostrarUsuarios.setText("Mostrar Usuarios");
        btnMostrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarUsuariosActionPerformed(evt);
            }
        });

        btnMostrarPrestamos.setText("Mostrar  Prestamos");
        btnMostrarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPrestamosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarPrestamos)
                    .addComponent(btnMostrarUsuarios)
                    .addComponent(btnMostrarLibros)
                    .addComponent(btnAgregarLibro)
                    .addComponent(jLabel1)
                    .addComponent(btnAgregarUsuario)
                    .addComponent(btnPrestarLibro))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarLibro)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnPrestarLibro)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarLibros)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarUsuarios)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarPrestamos)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed
        // TODO add your handling code here:
        AgregarLibro v = new AgregarLibro(b);

v.setVisible(true);
    }//GEN-LAST:event_btnAgregarLibroActionPerformed

    private void btnMostrarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarLibrosActionPerformed
        // TODO add your handling code here:
        MostrarLibros v = new MostrarLibros(b);

v.setVisible(true);
    }//GEN-LAST:event_btnMostrarLibrosActionPerformed

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        // TODO add your handling code here:
        AgregarUsuario v = new AgregarUsuario(b);

v.setVisible(true);
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void btnPrestarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarLibroActionPerformed
PrestarLibro v = new PrestarLibro(b);

v.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrestarLibroActionPerformed

    private void btnMostrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarUsuariosActionPerformed

MostrarUsuarios m = new MostrarUsuarios(b);

m.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarUsuariosActionPerformed

    private void btnMostrarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPrestamosActionPerformed
        // TODO add your handling code here:
        MostrarPrestamos m = new MostrarPrestamos(b);

m.setVisible(true);
    }//GEN-LAST:event_btnMostrarPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnMostrarLibros;
    private javax.swing.JButton btnMostrarPrestamos;
    private javax.swing.JButton btnMostrarUsuarios;
    private javax.swing.JButton btnPrestarLibro;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
